# Generated by Django 2.2.7 on 2019-11-15 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableColors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'available_colors',
            },
        ),
        migrations.CreateModel(
            name='AvailableSideNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'available_side_names',
            },
        ),
        migrations.CreateModel(
            name='AvailableSizeUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'available_size_units',
            },
        ),
        migrations.CreateModel(
            name='BasicProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'basic_products',
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Cares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'cares',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=20)),
                ('hex_code', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'colors',
            },
        ),
        migrations.CreateModel(
            name='FittingModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('height', models.IntegerField()),
                ('top', models.IntegerField()),
                ('waist', models.IntegerField()),
                ('shoe', models.IntegerField()),
            ],
            options={
                'db_table': 'fitting_models',
            },
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'parts',
            },
        ),
        migrations.CreateModel(
            name='PartsForCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.Categories')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.Parts')),
            ],
            options={
                'db_table': 'parts_for_categories',
            },
        ),
        migrations.CreateModel(
            name='SideNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'side_names',
            },
        ),
        migrations.CreateModel(
            name='SizeUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_unit', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'size_units',
            },
        ),
        migrations.CreateModel(
            name='SizeSorters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_size_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.AvailableSizeUnits')),
                ('part_for_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.PartsForCategories')),
            ],
            options={
                'db_table': 'size_sorters',
            },
        ),
        migrations.CreateModel(
            name='SizeFiguresForProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_figure', models.IntegerField()),
                ('basic_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.BasicProducts')),
                ('size_sorter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.SizeSorters')),
            ],
            options={
                'db_table': 'size_figures_for_products',
            },
        ),
        migrations.CreateModel(
            name='SideImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_image', models.URLField(max_length=3000)),
                ('available_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.AvailableColors')),
                ('available_side_names', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.AvailableSideNames')),
                ('basic_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.BasicProducts')),
            ],
            options={
                'db_table': 'side_images',
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('made_of', models.CharField(max_length=20)),
                ('made_by', models.CharField(max_length=20)),
                ('made_in', models.CharField(max_length=20)),
                ('elasticity', models.CharField(max_length=20)),
                ('texture', models.CharField(max_length=20)),
                ('thickness', models.CharField(max_length=20)),
                ('fitting_info', models.CharField(max_length=20)),
                ('basic_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.BasicProducts')),
                ('care', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.Cares')),
                ('fitting_models', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.FittingModels')),
            ],
            options={
                'db_table': 'product_info',
            },
        ),
        migrations.CreateModel(
            name='ModelImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_image', models.URLField(max_length=3000)),
                ('basic_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.BasicProducts')),
            ],
            options={
                'db_table': 'model_images',
            },
        ),
        migrations.AddField(
            model_name='basicproducts',
            name='available_color',
            field=models.ManyToManyField(through='clothing.AvailableColors', to='clothing.Colors'),
        ),
        migrations.AddField(
            model_name='basicproducts',
            name='available_size_unit',
            field=models.ManyToManyField(through='clothing.AvailableSizeUnits', to='clothing.SizeUnits'),
        ),
        migrations.AddField(
            model_name='basicproducts',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.Brands'),
        ),
        migrations.AddField(
            model_name='basicproducts',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.Categories'),
        ),
        migrations.AddField(
            model_name='availablesizeunits',
            name='basic_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.BasicProducts'),
        ),
        migrations.AddField(
            model_name='availablesizeunits',
            name='size_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.SizeUnits'),
        ),
        migrations.AddField(
            model_name='availablesidenames',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.Categories'),
        ),
        migrations.AddField(
            model_name='availablesidenames',
            name='side_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.SideNames'),
        ),
        migrations.AddField(
            model_name='availablecolors',
            name='basic_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.BasicProducts'),
        ),
        migrations.AddField(
            model_name='availablecolors',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.Colors'),
        ),
    ]
