# Generated by Django 2.2.7 on 2019-11-15 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191115_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='social_login_id',
            new_name='platform_id',
        ),
    ]
