# Generated by Django 2.2.7 on 2019-11-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191115_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialplatform',
            name='platform_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
